on: push
name: auto deploy on push
jobs:
  deploy:
    name: Deploy web app
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Deploy using FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: autodeploy.swostikapokharel.com.np
          exclude: |
              **/.git*
              **/.git*/**
              **/logs/**
              
